'use strict';
const $ = selector => document.querySelector(selector);
let csrf='', state={}, media=[], activeId=null;
const labels={name:'Nama',title:'Judul',summary:'Ringkasan',content:'Isi lengkap',hotel:'Hotel / kelas (referensi)',flight:'Penerbangan',duration:'Durasi',tutor:'Pembimbing',price:'Harga referensi (bukan harga otomatis terkini)',category:'Kategori',brochure:'Brosur gambar arsip',status:'Ketersediaan',validUntil:'Batas konfirmasi ketersediaan',position:'Jabatan',rating:'Nilai (1–5)',date:'Tanggal artikel',caption:'Keterangan foto',image:'Gambar',sourceNote:'Sumber / catatan verifikasi',published:'Terbitkan di website',order:'Urutan (angka kecil tampil lebih dulu)'};
const schemas={packages:['name','title','summary','content','hotel','flight','duration','tutor','price','category','brochure','status','validUntil'],teams:['name','position','content'],testimonials:['name','content','rating'],posts:['title','summary','content','date'],gallery:['title','caption']};
const limits={name:120,title:240,summary:600,content:24000,hotel:200,flight:200,duration:100,tutor:200,price:120,position:160,caption:2000,sourceNote:600};
function notify(text){$('#status').textContent=text;}
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
async function api(url,method='GET',data){const response=await fetch(url,{method,credentials:'same-origin',headers:{...(data?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},body:data?JSON.stringify(data):undefined});const value=await response.json();if(!response.ok){if(response.status===401){csrf='';$('#workspace').hidden=true;$('#login-panel').hidden=false;}throw new Error(value.error||'Permintaan gagal.');}return value;}
async function load(){[state,media]=await Promise.all([api('/api/content'),api('/api/media')]);$('#workspace').hidden=false;$('#login-panel').hidden=true;list();mediaList();}
function type(){return $('#collection').value;}
function list(){const root=$('#record-list');root.replaceChildren();for(const r of [...state[type()]].sort((a,b)=>a.order-b.order)){const b=node('button',r.name||r.title);b.type='button';b.append(node('small',`${r.published?'Terbit':'Draf'} · urutan ${r.order}`));b.addEventListener('click',()=>edit(r));root.append(b);}if(!root.children.length)root.append(node('p','Belum ada konten. Tambahkan catatan pertama.'));}
function mediaSelect(select,value){select.replaceChildren();const empty=node('option','Tanpa gambar');empty.value='';select.append(empty);for(const item of media){const option=node('option',item.url.split('/').pop());option.value=item.url;select.append(option);}select.value=value||'';}
function edit(record={}){
  activeId=record.id||null;const collection=type();$('#editor-title').textContent=activeId?'Edit konten':'Konten baru';$('#delete-record').hidden=!activeId;const fields=$('#fields');fields.replaceChildren();
  for(const key of [...schemas[collection],'image','sourceNote','published','order']){
    const label=node('label',labels[key]);label.htmlFor=`field-${key}`;let input;
    if(['image','brochure','category','status'].includes(key)){
      input=node('select');if(['image','brochure'].includes(key))mediaSelect(input,record[key]);else {const options=key==='category'?{umroh:'Umroh Reguler',plus:'Umroh Plus',wisata:'Wisata'}:{confirmation:'Wajib konfirmasi / arsip',available:'Tersedia (harus ada tanggal berlaku)',closed:'Ditutup'};for(const [value,text]of Object.entries(options)){const option=node('option',text);option.value=value;input.append(option);}input.value=record[key]||(key==='category'?'umroh':'confirmation');}
    }else if(['summary','content','caption','sourceNote'].includes(key)){input=node('textarea');input.rows=key==='content'?12:3;input.value=record[key]||'';}
    else{input=node('input');input.type=['date','validUntil'].includes(key)?'date':key==='published'?'checkbox':['rating','order'].includes(key)?'number':'text';if(key==='published')input.checked=record.published??false;else input.value=record[key]??(key==='order'?0:key==='rating'?5:key==='date'?new Date().toISOString().slice(0,10):'');if(input.type==='number'){input.min=key==='rating'?'1':'0';input.max=key==='rating'?'5':'9999';input.step='1';}}
    if(limits[key])input.maxLength=limits[key];if(key==='name'&&collection!=='packages')input.maxLength=160;if(key==='title'&&collection==='gallery')input.maxLength=200;if(key==='content')input.maxLength=({packages:24000,teams:3000,testimonials:5000,posts:30000})[collection];
    input.name=key;input.id=`field-${key}`;input.required=['name','title'].includes(key)||key==='date'||(key==='content'&&['testimonials','posts'].includes(collection))||(key==='image'&&collection==='gallery');fields.append(label,input);
    if(['image','brochure'].includes(key)){const preview=node('img',undefined,'field-preview');preview.alt='Pratinjau gambar';const refresh=()=>{preview.hidden=!input.value;if(input.value)preview.src=input.value;else preview.removeAttribute('src');};input.addEventListener('change',refresh);refresh();fields.append(preview);}
  }
  if(collection==='packages'){fields.append(node('p','Status tersedia hanya diterima jika tanggal batas konfirmasi masih berlaku. Setelah lewat, website otomatis kembali meminta konfirmasi. Harga arsip tidak dianggap penawaran baru.', 'field-help'));}
  $('#editor-panel').hidden=false;
}
function mediaList(){const root=$('#media-list');root.replaceChildren();for(const item of media){const card=node('div',undefined,'media-item');const img=node('img');img.src=item.url;img.alt='Gambar pustaka';img.loading='lazy';const remove=node('button','Hapus gambar','secondary');remove.type='button';remove.addEventListener('click',async()=>{if(!confirm('Hapus gambar ini secara permanen?'))return;try{await api(`/api/media/${item.url.split('/').pop()}`,'DELETE');media=await api('/api/media');mediaList();refreshImageOptions();notify('Gambar dihapus.');}catch(e){notify(e.message);}});card.append(img,node('code',item.url),remove);root.append(card);}}
function refreshImageOptions(){for(const select of document.querySelectorAll('#fields select'))if(['image','brochure'].includes(select.name)){const value=select.value;mediaSelect(select,value);select.dispatchEvent(new Event('change'));}}
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('#login-form button[type="submit"]');button.disabled=true;try{const result=await api('/api/login','POST',{password:$('#password').value});csrf=result.csrf;$('#password').value='';await load();notify('Berhasil masuk.');}catch(e){notify(e.message);}finally{button.disabled=false;}});
$('#logout').addEventListener('click',async()=>{try{await api('/api/logout','POST');csrf='';state={};$('#workspace').hidden=true;$('#editor-panel').hidden=true;$('#login-panel').hidden=false;notify('Sesi telah ditutup.');}catch(e){notify(e.message);}});
$('#collection').addEventListener('change',()=>{$('#editor-panel').hidden=true;activeId=null;list();});
$('#new-record').addEventListener('click',()=>edit());$('#cancel-edit').addEventListener('click',()=>{$('#editor-panel').hidden=true;activeId=null;});
$('#editor-form').addEventListener('submit',async event=>{event.preventDefault();const record={};for(const input of $('#editor-form').elements){if(!input.name)continue;record[input.name]=input.type==='checkbox'?input.checked:input.type==='number'?Number(input.value):input.value;}const button=$('#save-button');button.disabled=true;try{const saved=await api(`/api/content/${type()}${activeId?'/'+activeId:''}`,activeId?'PUT':'POST',record);await load();edit(saved);notify('Konten tersimpan. Website publik diperbarui.');}catch(e){notify(e.message);}finally{button.disabled=false;}});
$('#delete-record').addEventListener('click',async()=>{if(!activeId||!confirm('Hapus konten ini secara permanen?'))return;try{await api(`/api/content/${type()}/${activeId}`,'DELETE');activeId=null;$('#editor-panel').hidden=true;await load();notify('Konten dihapus.');}catch(e){notify(e.message);}});
$('#upload-form').addEventListener('submit',async event=>{event.preventDefault();const file=$('#upload').files[0];if(!file)return;if(file.size>5*1024*1024){notify('Gambar maksimal 5 MB.');return;}const button=$('#upload-form button[type="submit"]');button.disabled=true;try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=()=>reject(new Error('Gambar tidak dapat dibaca.'));reader.readAsDataURL(file);});const uploaded=await api('/api/media','POST',{data});media=await api('/api/media');mediaList();refreshImageOptions();$('#upload-form').reset();notify(`Gambar diunggah: ${uploaded.url}. Pilih melalui kolom gambar pada editor.`);}catch(e){notify(e.message);}finally{button.disabled=false;}});
(async()=>{try{const s=await api('/api/session');$('#setup-note').hidden=s.configured;if(s.authenticated){csrf=s.csrf;await load();}}catch(e){notify(e.message);}})();
